// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMAV5WN96Ujr1DCcXruWZeD9lmd55xtDw',
    appId: '1:510427170931:web:ff40f4279b6d5d6de4c206',
    messagingSenderId: '510427170931',
    projectId: 'ipsldocs',
    authDomain: 'ipsldocs.firebaseapp.com',
    storageBucket: 'ipsldocs.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5aAPgT0_BMVmjq3AbsERPuF-3Pqk5qvM',
    appId: '1:510427170931:android:79e1b083b6c00a5ee4c206',
    messagingSenderId: '510427170931',
    projectId: 'ipsldocs',
    storageBucket: 'ipsldocs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZAJ1fsCMDLmLNKlGvGAC9JBjGWnAZD1c',
    appId: '1:510427170931:ios:a83c9e7f663bad6de4c206',
    messagingSenderId: '510427170931',
    projectId: 'ipsldocs',
    storageBucket: 'ipsldocs.firebasestorage.app',
    iosBundleId: 'com.example.ipslDocs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZAJ1fsCMDLmLNKlGvGAC9JBjGWnAZD1c',
    appId: '1:510427170931:ios:a83c9e7f663bad6de4c206',
    messagingSenderId: '510427170931',
    projectId: 'ipsldocs',
    storageBucket: 'ipsldocs.firebasestorage.app',
    iosBundleId: 'com.example.ipslDocs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMAV5WN96Ujr1DCcXruWZeD9lmd55xtDw',
    appId: '1:510427170931:web:4be3be908c979d24e4c206',
    messagingSenderId: '510427170931',
    projectId: 'ipsldocs',
    authDomain: 'ipsldocs.firebaseapp.com',
    storageBucket: 'ipsldocs.firebasestorage.app',
  );
}
