//Ce fichier contient la liste des matières pour chaque filière et chaque niveau.

Map<String, List<String>> matiere = {
  "Cpi1": [
    "Analyse 1",
    "Algèbre 1",
    "Algorithmique",
    "Architecture des ordinateurs",
    "Mécanique 1",
    "Électrocinétique",
    "Français 1",
    "Anglais 1",
    "Outils de communication",
    "Humanités 1",

    // Semestre 2
    "Analyse 2",
    "Algèbre 2",
    "Informatique 2",
    "Introduction à la POO",
    "Bases de Données ",
    "Optique géométrique",
    "Électromagnétisme )",
    "Chimie",
    "Français 2",
    "Anglais 2",
    "Culture et communication 1",
  ],
  "Cpi2": [
    // --- Semestre 1 ---
    "Analyse 3",
    "Algèbre 3",
    "Probabilités",
    "Analyse numérique",
    "Calcul formel",
    "Mécanique 2",
    "Thermodynamique",
    "Physique 3",
    "Électronique",
    "Français 3",
    "Anglais 3",
    "Culture et communication 2",

    // --- Semestre 2 ---
    "Français 4",
    "Anglais 4",
    "Culture et communication 3",
    // --Specialité---
    "Electronique de puissance",
    "Electrotechnique",
    "Automatique",
    "Mécanique Appliquée",
    "Physique des materiaux",
    "Dessin technique",
    "Mecanique des fluides",
    "Réseau",
    "Signaux et Système",
        "Initiation aux Bases de données"
        "Système d’information",
  ],

  'GeIT1': [
    "Architecture des ordinateurs )",
    "Algorithmique ",
    "Système d'information",
    "Introduction aux réseaux",
    "Théorie du signal",
    "Recherche opérationnelle",
    "Analyse numérique",
    "Anglais ",
    "Droit du travail",
    // --- Semestre 6 ---
    "Base de données",
    "POO avancée",
    "Systèmes d'exploitation",
    "Services réseaux",
    "Transmission des données",
    "Traitement du signal",
    "Statistiques",
    "Analyse de données",
  ],
  "GeIT2": [
    "Théorie des langages et compilation",
    "Methodes de gestion de Projet logiciel",
    "Administration Base de données",
    "Complexité algorithmique",
    "Codage et Cryptographie",
    "Architecture logicielle",
    "Humanités 7",
    "Seminaires techniques",
    "Base de données avancées",
    "Sécurité des des systemes informatiques",
    "Systèmes embarqués",
    "Programmation et technologies web",
    "Developpement oriente composant J2EE",
    "Humanités 8",
  ],
  "GeIT3": [
    "Spécification formelle et vérification",
    "Contrôle Qualité logicielle",
    "Ergonomie logiciel",
    "Developpement WEB",
    "Developpement mobile",
  ],
  "GeC1": [
    "Hydraulique urbain",
    "Hydraulique",
    "Hydraulique Agricole",
    "Hydraulogie",
    "Mileux continus",
    "Fluides 1",
    "Mécanique des sols",
    "Théorie de poutes (RDM)",
    "Topographie",
    "Régles de représentations",
    "Systèmes Constructifs",
    "Anglais",
    "Techniques d'expression",
    "Différences finies",
    "Eléments finies",
    "Matériaux de construction",
    "Lois de comportement",
    "Béton armé 1",
    "Performances des bétons",
    "Calculs des fondations",
    "Géologie de l'ingénieur",
    "Gestion de la ressourse en eau",
    "Mécanique des fluides 2",
    "Systèmes des Poutres",
    "Construction Métallique 1",
    "Organisation de l'Entreprise",
  ],
  "GeC2": [
    "Mécanique des éléments ",
    "Dynamique des structures",
    "Algorithmes appliqués aux méthodes numériques",
    "Éléments finis et applications",
    "Physique du bâtiment )",
    "Génie civil des réseaux enterrés (assainissement)",
    "Thermique",
    "Construction métallique 2",
    "Projet de construction métallique",
    "Béton armé ",
    "Anglais",
    "Economie et Gestion 1",
    "Management des projets",
    "Méthodes et organisation",
    "Conception et innovation",
    "Recherche opérationnelles",
    "Calcul non linéaires des tructures",
    "Modélisation avancée",
    "Mécanique et ingéniérie des roches",
    "Béton précontraint 1",
    "Projet beton arm",
    "Trafic et Géométrie routière",
    "Transport",
  ],
  "GeC3": [
    "Aménagement des bassin et des rivières",
    "Elements Finis et Applications",
    "Hydrodynamique environnmental des fluides",
    "Mécanique des roches",
    "Ouvrages de soutenement et stabilité des pentes",
    "Technologie des grand ouvrages",
    "Urbanisme",
    "Anglais",
    "Management de projet",
    "Ethique-Ingénieur et société",
    "Droit Général",
  ],
  "GeM1": [
    "Thermodynamique Appliquée",
    "Circuits électriques 1",
    "Transferts de chaleurs 1",
    "Statique",
    "Construction mécanique 1",
    "Sciences des matériaux",
    "Résistance des matériaux",
    "Ondes et vibration",
    "Cinématique et dynamique",
    "Anglais",
    "Droit du travail",
    "Automatique 1",
    "Circuits électriques 2",
    "Electronique analogique",
    "Energie nouvelle et renouvelable",
    "Procédé de Fabrication",
    "Construction mécanique 2",
    "Résistance des matériaux",
    "Technique de Communication",
  ],
  "GeM2": [
    "Electronique numérique",
    "Installations électriques",
    "Automatique 2",
    "Mécanique des fluides 2",
    "Eléments de machine",
    "Fabrication mécanique",
    "Atelier mécanique",
    "Recherche Opérationnelle",
    "Comptabilité Analogique",
    "Anglais",
    "Automatisme",
    "Machines électriques",
    "Electronique de puissance",
    "Moteurs turbines et compresseurs",
    "Systèmes hydrauliques et lubrification",
    "CAO + DAO",
    "Gestion de la production",
    "Analyse et conception de systèmes d'information",
  ],
  "GeM3": [
    "Réseaux électriques",
    "Froid et climatisation",
    "Machines hydrauliques",
    "Informatiques industrielles",
    "Plomberie bâtiment",
    "Plomberie industrielle",
    "Administration de l'entreprise",
    "Gestion de projets d'ingénieur",
    "Anglais",
    "Gestion de projets",
    "Sociologie de l'entreprise",
  ],
};
/*'Cpi1',
'GeM1',
'GeM2',
'GeM3',
'GeC1',
'GeC2',
'GeC3',*/
