name: Build & Release Flutter

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Create .env
        run: echo "${{ secrets.FLUTTER_ENV }}" > app/ipsl_docs/.env

      - name: Create google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICE_JSON }}" | base64 -d > app/ipsl_docs/android/app/google-services.json

      - name: Check JSON validity
        run: jq . app/ipsl_docs/android/app/google-services.json

      - name: Create Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/ipsl_docs/android/app/mykey.jks

      - name: Get App Version
        id: version
        working-directory: app/ipsl_docs
        run: |
          APP_VERSION=$(grep '^version:' pubspec.yaml | awk '{print $2}')
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.7"
          channel: stable

      - name: Install Dependencies
        working-directory: app/ipsl_docs
        run: flutter pub get

      - name: Disable watchers (CI fix)
        run: |
          echo "FLUTTER_SUPPRESS_WATCHER=true" >> $GITHUB_ENV
          echo "GRADLE_OPTS=-Dorg.gradle.vfs.watch=false" >> $GITHUB_ENV

      - name: Build APKs
        working-directory: app/ipsl_docs
        run: flutter build apk --split-per-abi

      - name: Rename APKs with version
        working-directory: app/ipsl_docs/build/app/outputs/flutter-apk
        run: |
          mv app-armeabi-v7a-release.apk ipsl_docs-${{ env.APP_VERSION }}-arme32.apk
          mv app-arm64-v8a-release.apk ipsl_docs-${{ env.APP_VERSION }}-arm64.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app/ipsl_docs/build/app/outputs/flutter-apk/ipsl_docs-${{ env.APP_VERSION }}-armeabi.apk
            app/ipsl_docs/build/app/outputs/flutter-apk/ipsl_docs-${{ env.APP_VERSION }}-arm64.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
